package com.miaoshaproject.dao;

import com.miaoshaproject.dataobject.StockDO;
import org.apache.ibatis.annotations.Param;

public interface StockDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Fri Apr 19 21:54:12 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Fri Apr 19 21:54:12 CST 2019
     */
    int insert(StockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Fri Apr 19 21:54:12 CST 2019
     */
    int insertSelective(StockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Fri Apr 19 21:54:12 CST 2019
     */
    StockDO selectByPrimaryKey(Integer id);
    StockDO selectByItemId(Integer id);
    //@Param 指明mabatis取值
    int decreaseStock(@Param("itemId") Integer itemId, @Param("amount")Integer amount);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Fri Apr 19 21:54:12 CST 2019
     */
    int updateByPrimaryKeySelective(StockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Fri Apr 19 21:54:12 CST 2019
     */
    int updateByPrimaryKey(StockDO record);
}